apiVersion: v1
kind: PersistentVolume

metadata:
  name: validation-pv

spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: manual

  hostPath:
    path: /run/desktop/mnt/host/c/WEATHERMLOPS/validation_dataset